GET http://localhost:3000/api/professor
###

GET http://localhost:3000/api/degree
###

GET http://localhost:3000/api/subject
###

GET http://localhost:3000/api/activity
###

GET http://localhost:3000/api/register
###

GET http://localhost:3000/api/professor/1/registers
###



